name: 'App Store Connect Build Wait'
description: 'Wait for App Store Connect build processing to complete'
author: 'yorifuji'

branding:
  icon: 'clock'
  color: 'blue'

inputs:
  issuer-id:
    description: 'App Store Connect API Issuer ID'
    required: true
  key-id:
    description: 'App Store Connect API Key ID'
    required: true
  key:
    description: 'App Store Connect API Private Key'
    required: true
  bundle-id:
    description: 'Bundle ID of the app'
    required: true
  version:
    description: 'Version to check (e.g., "1.2.0")'
    required: true
  build-number:
    description: 'Build number to check'
    required: true
  timeout:
    description: 'Timeout in seconds (60-1200)'
    default: '1200'
    required: false
  interval:
    description: 'Polling interval in seconds'
    default: '60'
    required: false

outputs:
  build-id:
    description: 'ID of the processed build'
  processing-state:
    description: 'Final processing state'
  version:
    description: 'Version of the build'
  build-number:
    description: 'Build number'
  elapsed-time:
    description: 'Time taken for processing in seconds'

runs:
  using: node20
  main: dist/index.js
