name: Release

run-name: Release for ${{ inputs.bump }}

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: Choose the type of bump
        default: patch
        options:
          - major
          - minor
          - patch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: yorifuji/next-latest-release@c5d1f40bd8800a595c2dd688947054b27fbe2ffd # v1.1.0
        id: next-release
        with:
          bump: ${{ inputs.bump }}

      - name: Configure git
        env:
          GIT_USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          GIT_USER_NAME: "github-actions[bot]"
        run: |
          git config --local user.name "$GIT_USER_NAME"
          git config --local user.email "$GIT_USER_EMAIL"

      - name: Update package.json version
        run: |
          npm version ${{ steps.next-release.outputs.version-number }} --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "chore: bump version to ${{ steps.next-release.outputs.version }}"
          git push origin main

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -f "${{ steps.next-release.outputs.version }}"
          git push -f origin "${{ steps.next-release.outputs.version }}"

          git tag -f "${{ steps.next-release.outputs.version-major }}"
          git push -f origin "${{ steps.next-release.outputs.version-major }}"

          gh release create --generate-notes --latest "${{ steps.next-release.outputs.version }}"
